title: Max Kraan
email: max@mxkrn.com
url: https://www.mxkrn.com
author: Max Kraan
description: Personal website for Max kraan
skills: "Machine Learning Engineer - Audio and Music Technology"

color:
  primary: 434343
  secondary: ffffff
  secondary-dark: 434343

footer:
  copyright: Max Kraan
  location: Based in Berlin

social:
  - title: github
    url: https://www.github.com/mxkrn
  - title: linkedin
    url: https://www.linkedin.com/in/mxkrn/
  - title: envelope
    url: mailto:contact@mxkrn.com

# address:
#   - line: Blücherstraße 13
#   - line: 10961 Berlin

markdown: kramdown
permalink: pretty

default:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

sass:
  sass_dir: assets/css
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag